### ISSUE TITLE
Returning original in svgeez_sanitize

### ISSUE THREAD

**Issue by darylldoyle** [Blobfolio/svgeez#1]
In my opinion you shouldn't return the original svg in `svgeez_sanitize` if it can't be sanitised. 

Whilst it'll stop uploads if there isn't any way to sanitise it, this is the safer option especially as you can't be sure that all systems will be able to sanitise.

**Comment by joshstoik1** [comment]
Yeah, I think you're right. Originally I did that because every method had special module requirements, but the fallback now is just a lot of blood, sweat and tears. I'll update it.
